# Generated by Django 5.2.7 on 2025-11-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='university_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมลมหาวิทยาลัย'),
        ),
    ]
