# Generated by Django 5.2.7 on 2025-11-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_university_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='คณะ'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='university_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมลมหาวิทยาลัย'),
        ),
    ]
