# Generated by Django 5.2.7 on 2025-12-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_create_unified_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'verbose_name': 'โปรไฟล์ผู้ดูแลระบบ (Deprecated)', 'verbose_name_plural': 'โปรไฟล์ผู้ดูแลระบบ (Deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'โปรไฟล์นักศึกษา (Deprecated)', 'verbose_name_plural': 'โปรไฟล์นักศึกษา (Deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'verbose_name': 'โปรไฟล์อาจารย์ (Deprecated)', 'verbose_name_plural': 'โปรไฟล์อาจารย์ (Deprecated)'},
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='year',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='student_year',
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='รหัสอาจารย์'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='teacher_employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='รหัสอาจารย์'),
        ),
    ]
