# Generated by Django 5.2.7 on 2025-12-07 21:26

import django.db.models.deletion
from django.db import migrations, models


def clear_invalid_faculty_data(apps, schema_editor):
    """Clear invalid faculty data before converting to ForeignKey"""
    UserProfile = apps.get_model('accounts', 'UserProfile')
    # Set all teacher_faculty to NULL/empty before conversion
    UserProfile.objects.filter(teacher_faculty__in=['None', '', None]).update(teacher_faculty=None)


def clear_invalid_major_data(apps, schema_editor):
    """Clear invalid major data before converting to ForeignKey"""
    UserProfile = apps.get_model('accounts', 'UserProfile')
    # Set all student_major to NULL/empty before conversion
    UserProfile.objects.filter(student_major__in=['None', '', None]).update(student_major=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_adminprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_code', models.CharField(max_length=20, unique=True, verbose_name='รหัสคณะ')),
                ('faculty_name', models.CharField(max_length=200, verbose_name='ชื่อคณะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัพเดท')),
            ],
            options={
                'verbose_name': 'คณะ',
                'verbose_name_plural': 'คณะ',
                'ordering': ['faculty_code'],
            },
        ),
        # Step 1: Remove old teacher_faculty field (CharField)
        migrations.RemoveField(
            model_name='userprofile',
            name='teacher_faculty',
        ),
        # Step 2: Add new teacher_faculty field (ForeignKey)
        migrations.AddField(
            model_name='userprofile',
            name='teacher_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='accounts.faculty', verbose_name='คณะ'),
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_code', models.CharField(max_length=20, unique=True, verbose_name='รหัสสาขา')),
                ('major_name', models.CharField(max_length=200, verbose_name='ชื่อสาขา')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัพเดท')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='accounts.faculty', verbose_name='คณะ')),
            ],
            options={
                'verbose_name': 'สาขา',
                'verbose_name_plural': 'สาขา',
                'ordering': ['faculty', 'major_code'],
            },
        ),
        # Step 1: Remove old student_major field (CharField)
        migrations.RemoveField(
            model_name='userprofile',
            name='student_major',
        ),
        # Step 2: Add new student_major field (ForeignKey)
        migrations.AddField(
            model_name='userprofile',
            name='student_major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.major', verbose_name='สาขา'),
        ),
    ]
