# Generated by Django 5.2.7 on 2025-11-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, unique=True, verbose_name='ปีการศึกษา')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('is_active', models.BooleanField(default=True, verbose_name='กำลังใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัพเดท')),
            ],
            options={
                'verbose_name': 'ปีการศึกษา',
                'verbose_name_plural': 'ปีการศึกษา',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True, verbose_name='รหัสวิชา')),
                ('course_name', models.CharField(max_length=200, verbose_name='ชื่อวิชา')),
                ('credit', models.IntegerField(verbose_name='หน่วยกิต')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('is_active', models.BooleanField(default=True, verbose_name='กำลังใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัพเดท')),
            ],
            options={
                'verbose_name': 'รายวิชา',
                'verbose_name_plural': 'รายวิชา',
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ลงทะเบียน')),
                ('status', models.CharField(choices=[('enrolled', 'ลงทะเบียน'), ('withdrawn', 'ถอน'), ('completed', 'เรียนจบ')], default='enrolled', max_length=20, verbose_name='สถานะ')),
            ],
            options={
                'verbose_name': 'การลงทะเบียน',
                'verbose_name_plural': 'การลงทะเบียน',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=10, verbose_name='เลขที่กลุ่ม')),
                ('capacity', models.IntegerField(default=30, verbose_name='จำนวนรับ')),
                ('room', models.CharField(blank=True, max_length=50, null=True, verbose_name='ห้องเรียน')),
                ('schedule', models.CharField(blank=True, max_length=200, null=True, verbose_name='ตารางเรียน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัพเดท')),
            ],
            options={
                'verbose_name': 'กลุ่มเรียน',
                'verbose_name_plural': 'กลุ่มเรียน',
                'ordering': ['semester', 'course', 'section_number'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField(choices=[(1, 'ภาคเรียนที่ 1'), (2, 'ภาคเรียนที่ 2'), (3, 'ภาคฤดูร้อน')], verbose_name='ภาคเรียน')),
                ('start_date', models.DateField(verbose_name='วันที่เริ่ม')),
                ('end_date', models.DateField(verbose_name='วันที่สิ้นสุด')),
                ('is_active', models.BooleanField(default=True, verbose_name='กำลังใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัพเดท')),
            ],
            options={
                'verbose_name': 'ภาคเรียน',
                'verbose_name_plural': 'ภาคเรียน',
                'ordering': ['-academic_year', 'semester_number'],
            },
        ),
    ]
