# Generated by Django 5.2.7 on 2025-11-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'รอลงทะเบียน'), ('enrolled', 'ลงทะเบียน'), ('withdrawn', 'ถอน'), ('completed', 'เรียนจบ')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
    ]
