# Generated by Django 5.2.7 on 2025-11-05 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=100, unique=True, verbose_name='Token สำหรับ QR Code')),
                ('session_date', models.DateField(verbose_name='วันที่เช็คชื่อ')),
                ('session_time', models.TimeField(verbose_name='เวลาเช็คชื่อ')),
                ('duration_minutes', models.IntegerField(default=15, verbose_name='ระยะเวลาเช็คชื่อ (นาที)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานได้')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('expires_at', models.DateTimeField(verbose_name='หมดอายุ')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academic.section', verbose_name='กลุ่มเรียน')),
            ],
            options={
                'verbose_name': 'เซสชันเช็คชื่อ',
                'verbose_name_plural': 'เซสชันเช็คชื่อ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'มา'), ('late', 'สาย'), ('absent', 'ขาด'), ('excused', 'ลากิจ')], default='present', max_length=20, verbose_name='สถานะ')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่สแกน')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='เวลาที่อัพเดท')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='นักศึกษา')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='แก้ไขโดย')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession', verbose_name='เซสชันเช็คชื่อ')),
            ],
            options={
                'verbose_name': 'บันทึกการเข้าเรียน',
                'verbose_name_plural': 'บันทึกการเข้าเรียน',
                'ordering': ['-scanned_at'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
