# Generated by Django 5.2.7 on 2025-11-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
    ]
