# Generated by Django 5.2.7 on 2025-11-05 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        ('attendance', '0007_remove_old_session_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-checked_in_at']},
        ),
        migrations.AlterModelOptions(
            name='attendancesession',
            options={'ordering': ['-session_datetime']},
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_proofs/', verbose_name='หลักฐานการเข้าเรียน'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'เข้าเรียน'), ('absent', 'ขาดเรียน'), ('late', 'มาสาย'), ('excused', 'มีเหตุผล')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='duration_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academic.section'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='session_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='session_time',
            field=models.TimeField(),
        ),
    ]
