# Generated by Django 5.2.7 on 2025-12-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendancerecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'ลาป่วย'), ('personal', 'ลากิจ'), ('other', 'อื่นๆ')], default='sick', max_length=20),
        ),
    ]
